version: '3.1'
services:
  db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
      MARIADB_DATABASE: "${MARIADB_DATABASE}"
      MARIADB_USER: "${MARIADB_USER}"
      MARIADB_PASSWORD: "${MARIADB_PASSWORD}"
    volumes:
      - "db:/var/lib/mysql"
      - "./sql:/docker-entrypoint-initdb.d"
      - "./seed:/seed"
    restart: always
  rest:
    image: quote-rest
    build: ./REST
    depends_on:
      - "db"
    restart: always
  web:
    image: quote-web
    build:
      context: ./Vue
      args:
        - "REST_URL=${REST_URL}"
    volumes:
      - "./nginx-default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "${WEB_PORT}:80"
    depends_on:
      - "rest"
    restart: always
volumes:
  db: